/**
 * 
 */
package com.asys.constants;

/**
 * @author ryan
 *
 */
public enum CommandName {
	CREATE_GATE, CREATE_FANOUT, CREATE_WIRE, CREATE_WIRE_EDGE, DELETE, MOVE, ROTATE, CHANGE_NUMBER_OF_INPORT, CHANGE_NUMBER_OF_OUTPORT, SELECT_WIRE, SELECT_WIRE_EDGE, SELECT_ELEMENT, SELECT_MULTI_ELEMENT, SELECT_GROUP_ELEMENT, SELECT_GROUP_MULTI_ELEMENT, DESELECT, UNDO, REDO, COPY, PASTE;
}
